<?xml version="1.0"?>
<package format="2">
  <name>robotnik_email</name>
  <version>0.2.2</version>
  <description>The robotnik_email package, based on RComponent structure. Email server to send messages through ROS</description>

  <maintainer email="rvasquez@robotnik.es">Robert Vasquez Zavaleta</maintainer>
  <maintainer email="jmnavarrete@robotnik.es">Juanma</maintainer>
  <maintainer email="rnavarro@robotnik.es">Román Navarro</maintainer>

  <author email="rvasquez@robotnik.es">Robert Vasquez Zavaleta</author>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend>

  <build_export_depend>rospy</build_export_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rcomponent</exec_depend>
  <build_depend>robotnik_alarms_msgs</build_depend>
  <build_depend>python-is-python3</build_depend>

  <test_depend>rcomponent</test_depend>
  <test_depend>robotnik_alarms_msgs</test_depend>
  <test_depend>python-is-python3</test_depend>
</package>
