sendgrid:
  sender: 'jmartinezojeda5upv@gmail.com'
  default_recipients:
    - 'jmartinez@robotnik.es'
    - 'jmartinezojeda5@gmail.com'
  api_key: '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' 