smtp:
  server: 'smtp.gmail.com'
  port: 25
  use_authentication: true
  username: 'robert96229@gmail.com'
  password: 'vgvmafcaqvsjjhbu'
  sender: 'robert96229@gmail.com'
  default_recipients:
    - 'rnavarro@robotnik.es'
    - 'rvasquez@robotnik.es'